env:
  global:
   - secure: "WiX0TsN48BIsU4QXRXIBXzptms6mapdku9uZrY1LkuM2zSYAhLsbFtEMSV/mo6eUumk5wwk5YIUanC+YuXlf9uJrG9XLUROVBLnH0O5zXpnQOtAqG5TB8ERWV+nEIlfmOzsyNHF35qv88OGx/LL/F0bpB/6RZchirU3wnmghp8/kyoZSdxYEnxKKlvwxJnhCP2/Vpo9xQ/pJUQe3u0/ykx5KH97dNnfEcIExag4C6hu4B0K8qnZj2VhrY7MrmG3uNEuRIFIOnox82CGzgZccWJBfkZh04dwgVHFmFkr81GcmQPOXHfuJ8WsChPrep/fTzTiDY5OZfU7acb8IjIAYO/D6ZeGGeAWh0TLN+y8ABDuIyZ9eUjSH/YXN6gEmnM718CKEipSobZ1raXVVI4PezrQxW1qBaTu1n9Xgx1qwTumNRvTmDGiupskXeeCJqk4HJNzux1VARzJ+qWI6qob5eCIs3vG1+HEBBIgxMESMrFmCA0by40Fr3aj4Yob+7LwuPVSbUM4qUduKL0v/I6v9tf9CHMeokrxA6yBLlZ9frkY2WeEsm03YRrlDSpU1Whb+u3MgcFV6O9r31PejoI+C/QrBRI7w+gQbpgtBv7qoWQy4M/8UVTUpHbweouCd8FGnPQKaFmWw8FQNXnXZGX/deKHs4A1KSI5MeJrThOmR5YE="
language: node_js
node_js:
- '4.0'
install:
- npm rebuild node-sass 
script: npm run build
deploy:
  provider: script
  script: npm run deploy
  on:
    branch: master
